{
  "apiVersion": "v1",
  "data": {
    "Caddyfile": ":80 {\n  root * /srv\n  file_server\n  encode gzip\n}\n"
  },
  "kind": "ConfigMap",
  "metadata": {
    "name": "caddyfile",
    "namespace": "photo-organizer"
  }
}
